target("render")
    set_kind("phony")
    set_default(false)
    set_group("modules")
    add_files("*.cppm", {public = true})
    add_files("*.cpp", {public = true})
    add_files("text/*.cpp", {public = true})
    add_deps("gfx", "asset", "gui")
    add_packages("range-v3", "freetype", {public = true})
