target("tests")
    set_kind("phony")
    set_default(false)
    set_group("test")
    add_deps("unit_tests")

target("unit_tests")
    set_default(false)
    set_group("test")
    set_rundir("$(projectdir)")
    add_deps("engine", "test_utils")
    add_files("unit_test_main.cpp")
    add_files("../**/test/*.cpp")
    remove_files("../*/test/*_test_main.cpp")
    remove_files("../*/test/*_benchmark.cpp")
