option("ispc")
    set_description("Enable or disable ispc for building math library")
    set_default(true)
    set_showmenu(true)
    add_defines("USE_ISPC")
option_end()

target("ispc_math")
    set_kind("static")
    set_default(false)
    add_rules("utils.ispc")
    add_files("ispc/*.ispc", "ispc/*.cpp")
    add_includedirs("ispc", {public = true})
