add_requires("libpng", "assimp", "libjpeg-turbo", "crossguid")

target("parser")
    set_kind("static")
    add_files("src/parser/*.cpp")
    add_includedirs("include", {public = true})
    add_deps("core", "math")
    add_packages("libpng", "assimp", "spdlog", "libjpeg-turbo", "crossguid")

target("mesh")
    set_kind("static")
    add_files("src/mesh.cpp")
    add_includedirs("include", {public = true})
    add_deps("core", "math")
    add_packages("spdlog", "crossguid", "magic_enum")