add_requires("libpng", "assimp", "libjpeg-turbo", "crossguid")

target("parser")
    set_kind("static")
    add_files("src/parser/*.cpp")
    remove_files("src/parser/assimp.cpp")
    add_includedirs("include", {public = true})
    add_deps("core", "math", "mesh")
    add_packages("libpng", "assimp", "spdlog", "libjpeg-turbo", "crossguid")

target("material")
    set_kind("static")
    add_files("src/material.cpp")
    add_includedirs("include", {public = true})
    add_deps("core", "math")
    add_packages("spdlog", "crossguid")

target("mesh")
    set_kind("static")
    add_files("src/mesh.cpp")
    add_includedirs("include", {public = true})
    add_deps("core", "math", "utils")
    add_packages("spdlog", "magic_enum")
    add_packages("crossguid", {public = true})