target("asset")
    set_kind("phony")
    set_default(false)
    set_group("modules")
    add_files("*.cppm", {public = true})
    add_files("*.cpp")
    add_deps("core", "math", "gfx", "ecs", "utils")
    add_packages("libpng", "assimp", "libjpeg-turbo", "nlohmann_json", "fx-gltf", "range-v3", {public = true})
