target("core_tests")
    set_default(false)
    add_files("memory_test.cpp", "file_io_manager_test.cpp", "timer_test.cpp", "core_test_main.cpp")
    add_deps("core", "test_utils")
    set_group("test/core")

target("core_benchmarks")
    set_default(false)
    add_files("memory_benchmark.cpp")
    add_deps("core", "test_utils")
    set_group("benchmark/core")
