target("hid")
    set_kind("phony")
    set_default(false)
    set_group("modules")
    add_files("input_manager.cppm", {public = true})
    add_files("*.cpp", {public = true})
    add_deps("core", "math")
