target("ecs_tests")
    set_default(false)
    add_files("ecs_test.cpp", "ecs_test_main.cpp")
    add_deps("ecs", "test_utils")
    set_group("test/ecs")

target("ecs_benchmarks")
    set_default(false)
    add_files("ecs_benchmark.cpp")
    add_deps("ecs", "test_utils")
    set_group("benchmark/ecs")
