target("pbr-demo-game-lib")
    set_default(has_config("examples"))
    set_kind("static")
    add_files("pbr_demo.cppm", {public = true})
    add_deps("engine")

target("pbr-demo-game")
    set_default(has_config("examples"))
    add_files("game.cpp")
    add_deps("pbr-demo-game-lib")
    set_rundir("$(projectdir)")

target("pbr-demo-game-editor")
    set_default(has_config("examples"))
    add_files("editor.cpp")
    add_deps("pbr-demo-game-lib", "hitagi_editor")
    set_rundir("$(projectdir)")
