target("gfx_test")
    set_default(false)
    add_files("gfx_test.cpp")
    add_deps("gfx", "asset", "utils", "test_utils")
    set_group("test/gfx")
    set_rundir("$(projectdir)")

target("shader_compiler_test")
    set_default(false)
    add_files("shader_compiler_test.cpp")
    add_deps("gfx", "utils", "test_utils")
    set_group("test/gfx")

target("device_test")
    set_default(false)
    add_files("device_test.cpp")
    add_deps("app", "gfx", "asset", "utils", "test_utils")
    set_group("test/gfx")
    set_rundir("$(projectdir)")

target("render_graph_test")
    set_default(false)
    add_files("render_graph_test.cpp")
    add_deps("app", "gfx", "asset", "test_utils")
    set_group("test/gfx")
    set_rundir("$(projectdir)")
