target("editor")
    add_files("*.cppm")
    add_files("*.cpp")
    add_files("component/*.cpp")
    add_deps("engine")
    add_includedirs(".")
    add_packages("magic_enum", "nlohmann_json", "spdlog")
    set_rundir("$(projectdir)")
    set_default(true)

target("editor_tests")
    set_default(false)
    set_group("test")
    add_files("*.cppm")
    add_files("editor.cpp")
    add_files("component/*.cpp")
    add_files("scene_viewport.cpp")
    add_files("image_viewer.cpp")
    add_files("imfilebrowser.cpp")
    add_files("test/*.cpp")
    add_deps("engine")
    add_includedirs(".")
    add_packages("gtest", "gmock", "spdlog")
    set_rundir("$(projectdir)")
