target("editor")
    add_files("main.cpp")
    add_deps("hitagi_editor")
    set_rundir("$(projectdir)")
    set_default(true)

target("editor_tests")
    set_default(false)
    set_group("test")
    add_files("test/*.cpp")
    add_deps("hitagi_editor", "hitagi_interop_test")
    set_rundir("$(projectdir)")
