target("editor")
    add_files("main.cpp")
    add_deps("hitagi_editor")
    add_packages("spdlog")
    set_rundir("$(projectdir)")
    set_default(true)

target("editor_tests")
    set_default(false)
    set_group("test")
    add_files("test/*.cpp")
    add_deps("hitagi_editor")
    add_packages("gtest", "gmock", "spdlog")
    set_rundir("$(projectdir)")
